name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      Solution_Name: DotNetTemplate       

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

#    - name: Setup MSBuild.exe
#      uses: microsoft/setup-msbuild@v2

    - name: Build application
      run: dotnet build --configuration/p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
